apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.task.cattle.io/workloadselector: deployment-tz-hera
  name: hera
  namespace: tz
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.task.cattle.io/workloadselector: deployment-tz-hera
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8003,"dnsName":"hera","kind":"ClusterIP","name":"8003tcp2","protocol":"TCP"}]]'
      labels:
        workload.task.cattle.io/workloadselector: deployment-tz-hera
    spec:
      containers:
        - command:
            - java
            - -Djava.security.egd=file:/dev/./urandom
            - -Dskywalking.trace.ignore_path=/eureka/**
            - -server
            - -jar
            - -Xms4G
            - -Xmx4G
            - -Xmn2G
            - /app/app.jar
            - --eureka.instance.prefer-ip-address=true
            - --apollo.meta=http://10.39.52.71:8080
          env:
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              valueFrom:
                configMapKeyRef:
                  key: backend_service
                  name: collector
          image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
          imagePullPolicy: IfNotPresent
          name: hera
          ports:
            - containerPort: 8003
              name: 8003tcp2
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: admin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
