apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.task.cattle.io/workloadselector: deployment-cp-member
  name: member
  namespace: cp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.task.cattle.io/workloadselector: deployment-cp-member
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8003,"dnsName":"member","kind":"ClusterIP","name":"8003tcp2","protocol":"TCP"}]]'
      labels:
        workload.task.cattle.io/workloadselector: deployment-cp-member
    spec:
      containers:
        - command:
            - java
            - -Djava.security.egd=file:/dev/./urandom
            - -Dskywalking.trace.ignore_path=/eureka/**
            - -jar
            - -Xms256m
            - -Xmx512m
            - /app/app.jar
            - --eureka.instance.prefer-ip-address=true
            - --apollo.meta=http://10.39.52.71:8080
            - --env=DEV
          env:
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              valueFrom:
                configMapKeyRef:
                  key: backend_service
                  name: collector
          image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
          imagePullPolicy: IfNotPresent
          name: member
          ports:
            - containerPort: 8003
              name: 8003tcp2
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /opt/baofu/cer
              name: vol1
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: zvos
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: test-pv
